### ISSUE TITLE
Install troubleshooting utilities

### ISSUE THREAD

**Issue by neojaw** [neobotix/robot-setup-tool#40]
`netcat`, `can-utils`, `lm-sensors`, ...

**Comment by padhupradheep** [comment]
why do we need can-utils by default?

**Comment by neojaw** [comment]
In case we ever need to check the CAN bus which is not unusual. Then it is convenient it is already there.

Also, when we troubleshoot with a customer remotely we can just tell them the commands to run, with no need to explain package installation. Keep in mind they might not be Linux experts, there might be no internet connection (allowed), they might have changed permissions and passwords etc.

There are probably a few more tools that fall into this category...
