### ISSUE TITLE
Galactic nav2_behaviors Problem

### ISSUE THREAD

**Issue by bekirbostanci** [neobotix/robot-setup-tool#9]
I decided to switch from foxy version to galactic but when I try to build it says nav2_behaviors package not found. 
When I checked from nav2, I saw that there is no such package for the galactic version. 
Is there anything I need to update? 
Should I go back to foxy or work on galactic?

```
--- stderr: neo_nav2_bringup                         
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findnav2_behaviors.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "nav2_behaviors", but CMake did not find one.

  Could not find a package configuration file provided by "nav2_behaviors"
  with any of the following names:

    nav2_behaviorsConfig.cmake
    nav2_behaviors-config.cmake

  Add the installation prefix of "nav2_behaviors" to CMAKE_PREFIX_PATH or set
  "nav2_behaviors_DIR" to a directory containing one of the above files.  If
  "nav2_behaviors" provides a separate development package or SDK, be sure it
  has been installed.


---
Failed   <<< neo_nav2_bringup [5.44s, exited with code 1]

Summary: 6 packages finished [5.66s]
  1 package failed: neo_nav2_bringup
  1 package had stderr output: neo_nav2_bringup

```

**Comment by padhupradheep** [comment]
Thanks for raising it. 

Unfortunately, we somehow missed to update this [particular line in the bash script](https://github.com/neobotix/robot-setup-tool/blob/da318f57b095d246e0d86fee22979ddd431e8b75/package-setup/setup-mpo_700.sh#L37) to point towards the galactic branch. 

I’ll do the update and you can start working with Galactic

**Comment by padhupradheep** [comment]
If you are using simulation, it has now been already updated.

**Comment by bekirbostanci** [comment]
Thank you for your fast reply.

**Comment by padhupradheep** [comment]
I’ll just leave it open, because I still have to fix for other setup scripts

**Comment by padhupradheep** [comment]
fixed
